title: BSides Oslo - May 23rd, 2019
description: BSides is an inclusive information security event that is focused on learning and sharing.
event: BSides Oslo
location: MESH
date: May 23rd, 2019
email_info: info@bsidesoslo.no
email_sponsorship: sponsors@bsidesoslo.no
email_cfp: cfp@bsidesoslo.no
ticket_store: https://www.deltager.no/iOFJKxGjJF7EoMLYv7L6Lz08YNlO
cfp_form: 
twitter_username: oslobsides

collections:
  talks:
    output: true
    layout: talks

sponsors:
  gold:
  - name: Nagarro
    logo: Nagarro.png
    website: https://www.nagarro.com/en
  - name: Bouvet
    logo: Bouvet.png
    website: https://www.bouvet.no
  - name: Basefarm
    logo: Basefarm.png
    website: https://www.basefarm.com/no/
  standard:
  - name: TrustedSec
    logo: trustedsec.png
    website: https://www.trustedsec.com/
  - name: Transcendent Group
    logo: Transcendent.png
    website: https://transcendentgroup.com/
  - name: Gelato
    logo: Gelato.png
    website: https://gelato.com
  - name: BDO Cybersecurity
    logo: BDOcybersecurity.png
    website: https://www.bdo.no/nb-no/tjenester/radgivning/cybersecurity
  - name: Paranoia
    logo: Paranoia.png
    website: https://paranoia.watchcom.no/
  - name: Sopra Steria
    logo: SopraSteria.png
    website: https://www.soprasteria.no/       
  community:
  - name: Blaze Information Security
    logo: Blaze.png
    website: https://www.blazeinfosec.com/
  - name: TurtleSec
    logo: turtlesec.png
    website: https://turtlesec.no/
  - name: ISACA
    logo: isaca.png
    website: http://engage.isaca.org/norwaychapter/
  - name: Hack The Box
    logo: hackthebox.png
    website: https://www.hackthebox.eu/  
  - name: Secure Practice
    logo: SecurePractice.png
    website: https://mailrisk.com
   

exclude: ['src', 'node_modules', 'gulpfile.js','.sass-cache']

markdown: kramdown
kramdown:
  input: GFM

defaults:
- scope:
    path: ""
  values:
    layout: "default"
